"""
Django settings for cognitivestyle project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os, platform

from django.conf.global_settings import TEMPLATE_CONTEXT_PROCESSORS, STATICFILES_FINDERS

#where are we?
ME_DEV = ['grendel', 'chiron']
ME = platform.node()

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SECURE_DIR = os.path.join(BASE_DIR,'secret')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY_LOCATION = os.path.join(SECURE_DIR,'secret_key')
with open(SECRET_KEY_LOCATION) as file:
    SECRET_KEY = file.read().strip()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = ME in ME_DEV


ALLOWED_HOSTS = [
    'kraemerlab.dartmouth.edu',
    'localhost',
]

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'compressor',
    'cognitivestyleapp',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'cognitivestyle.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'cognitivestyleapp', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cognitivestyle.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

if ME in ME_DEV:
    DB_ENGINE = 'django.db.backends.mysql'
    DB_HOST = 'localhost'
    DB_PORT = '3306'
    DB_NAME = 'cognitivestyledb'
    DB_USER = 'alex'
    DB_PW = 'kniggit'
else:
    DB_ENGINE = 'django.db.backends.mysql'
    DB_HOST = 'localhost'
    DB_PORT = '3306'
    DB_NAME = 'cognitivestyledb'
    DB_USER = 'kraemerlab'
    
    DB_PW_LOCATION = os.path.join(SECURE_DIR,'mysql_db_pw')
    with open(DB_PW_LOCATION) as file:
        DB_PW = file.read().strip()

DATABASES = {
	'default': {
		'ENGINE': DB_ENGINE,
		'NAME': DB_NAME,
		'USER': DB_USER,
		'PASSWORD': DB_PW,
		'HOST': DB_HOST,
		'PORT': DB_PORT
	}
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

STATICFILES_FINDERS += (
    'compressor.finders.CompressorFinder',
)

# compressor
COMPRESS_PRECOMPILERS = (
    ('text/x-sass', 'sass "{infile}" "{outfile}"'),
    ('text/x-scss', 'sass --scss --compass "{infile}" "{outfile}"'),
    ('text/coffeescript', 'coffee --compile --stdio'),
)

COMPRESS_CSS_FILTERS = (
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.CSSMinFilter',
)

COMPRESS_JS_FILTERS = (
    'compressor.filters.jsmin.JSMinFilter',
)

#if ME in ME_DEV:
if False:
    COMPRESS_ENABLED = False
    COMPRESS_OFFLINE = False
else:
    COMPRESS_ENABLED = True
    COMPRESS_OFFLINE = True
